# -*- coding: utf-8 -*-
"""sistema_de_auditoria.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoP9ciBsY38GfTArEwqC2iPXqjWMMkGI

# Sistema de Auditoria de Recursos Corporativos
> Luis Plinio Cornelio Mota
"""

import time
from functools import wraps

def auditor(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        print("="*50)
        print("RELATÓRIO DE AUDITORIA DE RECURSOS CORPORATIVOS")
        print(f"Iniciando cálculo... Argumentos: {args} {kwargs}")
        print("="*50)

        inicio = time.perf_counter()
        resultado = func(*args, **kwargs)
        fim = time.perf_counter()

        print(f"\nCálculo finalizado em: {fim - inicio:.6f} segundos.")
        print("="*50)
        return resultado
    return wrapper

setores_da_empresa = {
    "Matriz": {
        "TI": {
            "Infraestrutura": {
                "Servidores": 15000,
                "Redes": 12000,
                "Seguranca": 10000
            },
            "Desenvolvimento": {
                "Backend": 20000,
                "Frontend": 18000,
                "Mobile": 16000
            },
            "Suporte": {
                "HelpDesk": 7000,
                "Manutencao": 5000
            }
        },
        "RH": {
            "Recrutamento": {
                "Entrevistas": 4000,
                "DivulgacaoVagas": 3000
            },
            "Treinamento": {
                "Cursos": 5000,
                "Workshops": 2500
            }
        },
        "Financeiro": {
            "Contabilidade": {
                "FolhaPagamento": 12000,
                "Impostos": 9000
            },
            "Auditoria": {
                "AuditoriaInterna": 6000,
                "AuditoriaExterna": 8000
            }
        }
    }
}

@auditor
def calcular_orcamento(estrutura, *departamentos_ignorados, **config_cambio):
    def recursao(dados):
        soma = 0
        if isinstance(dados, dict):
            for chave, valor in dados.items():
                if chave in departamentos_ignorados:
                    continue
                if isinstance(valor, dict):
                    soma += recursao(valor)
                elif isinstance(valor, (int, float)):
                    soma += valor
        return soma

    valor_base = recursao(estrutura)

    taxa = config_cambio.get("taxa_cambio", 1.0)
    moeda = config_cambio.get("moeda_destino", "BRL")

    valor_final = valor_base * taxa
    return valor_final, moeda

resultado, moeda = calcular_orcamento(
    setores_da_empresa,
    "Suporte", "Treinamento",
    moeda_destino="USD", taxa_cambio=0.20
)

print(f"O orçamento auditado (ajustado) é: {moeda} {resultado:,.2f}")